"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 14:25:36.553965
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('source', sa.Enum('golfdb', 'self_labeled', 'mixed', name='dataset_source'), nullable=False),
    sa.Column('manifest_uri', sa.String(length=500), nullable=True),
    sa.Column('num_samples', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fault_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_signature', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='job_status'), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'run_after'], unique=False)
    op.create_index(op.f('ix_jobs_subject_id'), 'jobs', ['subject_id'], unique=False)
    op.create_table('labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('corrected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_labels_target', 'labels', ['target_type', 'target_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('club_used', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('checkpoint_uri', sa.String(length=500), nullable=True),
    sa.Column('trained_on_dataset_id', sa.UUID(), nullable=True),
    sa.Column('eval_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('active', 'experimental', 'deprecated', name='model_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trained_on_dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version')
    )
    op.create_index(op.f('ix_models_task'), 'models', ['task'], unique=False)
    op.create_table('swings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('video_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('sync_offset_frames', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clip_start', sa.Integer(), nullable=False),
    sa.Column('clip_end', sa.Integer(), nullable=True),
    sa.Column('is_reference', sa.Boolean(), nullable=False),
    sa.Column('club_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swings_session_id'), 'swings', ['session_id'], unique=False)
    op.create_index('ix_swings_video_ids', 'swings', ['video_ids'], unique=False, postgresql_using='gin')
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_uri', sa.String(length=500), nullable=False),
    sa.Column('proxy_uri', sa.String(length=500), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('camera_role', sa.Enum('face_on', 'down_the_line', 'other', name='camera_role'), nullable=False),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('num_frames', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending_upload', 'uploaded', 'preprocessed', 'failed', name='video_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    op.create_index(op.f('ix_videos_session_id'), 'videos', ['session_id'], unique=False)
    op.create_table('club_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swing_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('track_uri', sa.String(length=500), nullable=False),
    sa.Column('num_frames', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['swing_id'], ['swings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_tracks_swing_id'), 'club_tracks', ['swing_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swing_id', sa.UUID(), nullable=False),
    sa.Column('user_symptom_text', sa.Text(), nullable=True),
    sa.Column('predicted_faults', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('human_confirmed_faults', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['swing_id'], ['swings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_swing_id'), 'diagnoses', ['swing_id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swing_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=20), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('event_ref', sa.Enum('address', 'toe_up', 'mid_backswing', 'top', 'mid_downswing', 'impact', 'mid_follow_through', 'finish', name='event_type'), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['swing_id'], ['swings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_swing_version', 'metrics', ['swing_id', 'pipeline_version'], unique=False)
    op.create_table('pose_3d_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swing_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('joint_uri', sa.String(length=500), nullable=False),
    sa.Column('method', sa.Enum('triangulation', 'monocular_lift', name='pose_3d_method'), nullable=False),
    sa.Column('error_estimate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['swing_id'], ['swings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pose_3d_sequences_swing_id'), 'pose_3d_sequences', ['swing_id'], unique=False)
    op.create_table('pose_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swing_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('keypoint_uri', sa.String(length=500), nullable=False),
    sa.Column('landmark_schema_version', sa.String(length=50), nullable=False),
    sa.Column('num_frames', sa.Integer(), nullable=False),
    sa.Column('mean_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['swing_id'], ['swings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pose_sequences_swing_id'), 'pose_sequences', ['swing_id'], unique=False)
    op.create_table('reference_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('archetype', 'reference_swing', name='profile_type'), nullable=False),
    sa.Column('source_swing_id', sa.UUID(), nullable=True),
    sa.Column('metric_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_swing_id'], ['swings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swing_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swing_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('address', 'toe_up', 'mid_backswing', 'top', 'mid_downswing', 'impact', 'mid_follow_through', 'finish', name='event_type'), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['swing_id'], ['swings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('swing_id', 'model_id', 'event_type')
    )
    op.create_index(op.f('ix_swing_events_swing_id'), 'swing_events', ['swing_id'], unique=False)
    op.create_table('comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('swing_id', sa.UUID(), nullable=False),
    sa.Column('reference_profile_id', sa.UUID(), nullable=False),
    sa.Column('alignment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metric_deltas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reference_profile_id'], ['reference_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['swing_id'], ['swings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_swing_id'), 'comparisons', ['swing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparisons_swing_id'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_swing_events_swing_id'), table_name='swing_events')
    op.drop_table('swing_events')
    op.drop_table('reference_profiles')
    op.drop_index(op.f('ix_pose_sequences_swing_id'), table_name='pose_sequences')
    op.drop_table('pose_sequences')
    op.drop_index(op.f('ix_pose_3d_sequences_swing_id'), table_name='pose_3d_sequences')
    op.drop_table('pose_3d_sequences')
    op.drop_index('ix_metrics_swing_version', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_diagnoses_swing_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_club_tracks_swing_id'), table_name='club_tracks')
    op.drop_table('club_tracks')
    op.drop_index(op.f('ix_videos_session_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index('ix_swings_video_ids', table_name='swings', postgresql_using='gin')
    op.drop_index(op.f('ix_swings_session_id'), table_name='swings')
    op.drop_table('swings')
    op.drop_index(op.f('ix_models_task'), table_name='models')
    op.drop_table('models')
    op.drop_table('sessions')
    op.drop_index('ix_labels_target', table_name='labels')
    op.drop_table('labels')
    op.drop_index(op.f('ix_jobs_subject_id'), table_name='jobs')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('fault_labels')
    op.drop_table('datasets')
    # ### end Alembic commands ###
    for name in ("camera_role", "video_status", "pose_3d_method", "event_type", "profile_type",
                 "model_status", "dataset_source", "job_status"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
