"""diagnosis loop columns

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-23 15:58:25.420604
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('rule_hits', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('diagnoses', sa.Column('inputs_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('diagnoses', sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('diagnoses', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('diagnoses', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('diagnoses', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnoses', 'confirmed_at')
    op.drop_column('diagnoses', 'error')
    op.drop_column('diagnoses', 'meta')
    op.drop_column('diagnoses', 'output')
    op.drop_column('diagnoses', 'inputs_snapshot')
    op.drop_column('diagnoses', 'rule_hits')
    # ### end Alembic commands ###
